In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
#Create a NumPy array arr of integers from 0 to 5 and print its data type.

import numpy as np 
arr = np.arange(6)
print("Array:",arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int32


In [7]:
#Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5,2.6,3.7])

import numpy as np 
arr = np.array([1.5,2.6,3.7])
is_float64 = arr.dtype = np.float64
print("float data type")




float data type


In [9]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np 
arr = np.array([3+4j,2+8j,6+5j],dtype = np.complex128)
print("Array:",arr)
print("Data type:",arr.dtype)


Array: [3.+4.j 2.+8.j 6.+5.j]
Data type: complex128


In [11]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])
arr_float32 = arr.astype(np.float32)

print("Array with float data type:",arr)
print("Data type:",arr_float32.dtype)

Array with float data type: [1 2 3 4 5 6 7 8 9]
Data type: float32


In [12]:
#Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np 

arr = np.array([1.1234567,2.3246778,3.2344309],dtype = np.float64)
arr_float32 = arr.astype(np.float32)

print("Array with float32 data type:",arr)
print("Data type:",arr_float32.dtype)

Array with float32 data type: [1.1234567 2.3246778 3.2344309]
Data type: float32


In [17]:
#Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
import numpy as np

def array_attributes(arr):
    
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)




Shape: (2, 3)
Size: 6
Data type: int32


In [19]:
#Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)



2


In [26]:
#Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes
import numpy as np

def item_size_info(array):
    item_size = array.itemsize
    total_size = array.nbytes
    return item_size, total_size

if __name__ == "__main__":
    array = np.array([1, 2, 3, 4, 5])
    item_size, total_size = item_size_info(array)
    print(f"Item size: {item_size} bytes")
    print(f"Total size: {total_size} bytes")




Item size: 4 bytes
Total size: 20 bytes


In [29]:
#Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np 
n = 6
create_zeros_array = np.zeros(n)
print(create_zeros_array)


[0. 0. 0. 0. 0. 0.]


In [34]:
#Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
import numpy.matlib as nm
matrix = nm.ones((3,4))
print("Matrix:",matrix)


Matrix: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
#Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 'step'ArithmeticError
import numpy as np 
arr = np.arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


In [38]:
#Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
import numpy as np 
arr = np.linspace(0.0,1.0,5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [39]:
#Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
import numpy as np 
n = 5
identity_matrix = np.eye(n)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# Write a function that takes a Python list and converts it into a NumPy array
import numpy as np
list = [1,2,"harshita","khushi",3+4j,5+6j,1.3,6.2]
arr = np.array(list)
print(arr)

['1' '2' 'harshita' 'khushi' '(3+4j)' '(5+6j)' '1.3' '6.2']


In [42]:
# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])

view_array = original_array.view()

view_array[0] = 10

print("Original array:", original_array)
print("View array:", view_array)



Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [43]:
#Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np 

array1 = np.array([12, 13, 14])
array2 = np.array([15, 16, 17])

concatenated_array = np.concatenate((array1, array2))
print(concatenated_array)

[12 13 14 15 16 17]


In [65]:
#Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy' concatenate`.
import numpy as np 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8],[11,12]])

concatenated_array = np.concatenate((array1,array2),axis = 1)
print("concatenated_array:",)
print(concatenated_array)

concatenated_array:
[[ 1  2  3  7  8]
 [ 4  5  6 11 12]]


In [66]:
# Write a function that vertically stacks multiple NumPy arrays given as a list  np.vstack
import numpy as np 
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
array3 = np.array([[7, 8, 9]])

stacks_array = np.vstack((array1,array2,array3))
print("stacks_array:",)
print(stacks_array)

stacks_array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
import numpy as np 
arr = np.arange(0,10,2)
print("Generated Integer Array:")
print(arr)


Generated Integer Array:
[0 2 4 6 8]


In [67]:
#Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
import numpy as np 
array = np.linspace(0,2,10)
print("Array:",)
print(array)

Array:
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [68]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (invclusive).

import numpy as np
arr = np.logspace(0,3,5)
print("array:",)
print(array)

array:
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [5]:
#Access the 3rd element from the given NumPy array.
# arr = np.array([10,20,30,40,50])
import numpy as np
arr = np.array([10,20,30,40,50]) 
third_element = arr[2]
print("Third_Element")
print(third_element)


Third_Element
30


In [7]:
#Retrieve the element at index (1, 2) from the 2D NumPy array.
# arr_2d = np.array([[1,2,3]
#                    [4,5,6]
#                    [7,8,9]])
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print(element)




6


In [8]:
#Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#     arr = np.array([3,8,2,10,5,7])
import numpy as np 

arr = np.array([3,8,2,10,5,7])
greater_than_five = arr[arr > 5]
print(greater_than_five)

[ 8 10  7]


In [9]:
#Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#    arr = np.array([1,2,3,4,5,6,7,8,9])
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9])
sliced_arr = arr[2:6]
print(sliced_arr)


[3 4 5 6]


In [11]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#          arr_2d = np.array([[1, 2, 3]
#                             [4, 5, 6]
#                             [7, 8, 9]])
import numpy as np 
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
sub_array = arr_2d[0:2 , 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [4]:
#Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
indices = np.array([(0, 1), (2, 0), (1, 2)])

row_indices, col_indices = zip(*indices)

extracted_elements = array[row_indices, col_indices]

print(extracted_elements)  




[2 7 6]


In [9]:
#Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,])
threshold = 5
filtered_arr = array[array > threshold]
print(filtered_arr)

[6 7 8 9]


In [17]:
#Create a NumPy function that extracts elements from a 2D array using row and column indices provided  in separate arrays.
import numpy as np 
array = np.array([[5 , 10 , 15],
                  [20 , 25 , 30],
                  [35 , 40 , 45]]) 

row_indices = np.array([0,1,2])
column_indices = np.array([1,2,0])
extracted_elements = array[row_indices , column_indices]
print(extracted_elements)

[10 30 35]


In [2]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np 
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr = arr+5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [3]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np 
arr1 = np.array([[2,3,4]])
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],       
                 [9,10,11,12]])
array = arr2 * arr1.T 
print(array)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [9]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting
import numpy as np
arr1 = np.array([1, 2, 3, 4])  
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
result = arr2 + arr1[:, np.newaxis]

print(result)


[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [10]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using broadcasting
import numpy as np 
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[4,5,6]])

result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [11]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]]) 
arr2 = np.array([[7, 8],
                 [9, 10]])    
arr2_expanded = arr2[:, :, np.newaxis]  
result = arr1 * arr2_expanded

print(result)


[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [13]:
#calculate column-wise mean mean for the given array:
# arr = np.array([[1,2,3] , [4,5,6])
import numpy as np 
arr = np.array([[1,2,3],
                [4,5,6]])

column_mean = np.mean(arr,axis=0)

print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [14]:
#find maximum value in each row of the given array:
# arr = np.array([[1,2,3],[4,5,6]])
import numpy as np 
arr = np.array([[1,2,3],
                [4,5,6]])

row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [16]:
# for the given array, find indices of maximum value in each column
# arr = np.array([[1,2,3] ,[4,5,6]])

import numpy as np 
arr = np.array([[1,2,3],
                [4,5,6]])

column_max_indices = np.argmax(arr,axis=0)
print(column_max_indices)


[1 1 1]


In [17]:
# for the given array, apply custom function to calculate moving sum alongs rows
# arr = np.array([[1,2,3],[4,5,6]])

import numpy as np 
arr = np.array([[1,2,3],
                [4,5,6]])

window_size = 2
result = np.zeros_like(arr)

result[: , :-1] = arr[: , :-1] + arr[: , 1:]
result[: , -1] = arr[:,-2] + arr[: , -1]

print(result)

[[ 3  5  5]
 [ 9 11 11]]


In [18]:
# in the given array, check if all elements in eacch column are even
# arr = np.array([[2,4,6],[3,5,7]])

import numpy as np 
arr = np.array([[2,4,6],
                [3,5,7]])
all_even_columns = np.all(arr % 2 == 0 , axis=0)

print(all_even_columns)

[False False False]


In [20]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple','banana','grapes','pineapple])

import numpy as np

arr = np.array(['apple', 'banana', 'grapes', 'pineapple'])
old_substr = 'apple'
new_substr = 'fruit'
vectorized_replace = np.vectorize(lambda x: x.replace(old_substr, new_substr))

result = vectorized_replace(arr)

print(result)



['fruit' 'banana' 'grapes' 'pinefruit']


In [21]:
# write a function that concatenates strings in a numpy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])

import numpy as np 

arr1 = np.array(["Hello","World"])
arr2 = np.array(["Open","AI"])

concatenated = np.char.add(arr1,arr2)
print(concatenated)

['HelloOpen' 'WorldAI']


In [22]:
#60. Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple','banana','grapes','pineapple'])

import numpy as np 
 
arr = np.array(['apple','banana','grapes','pineapple'])
max_length = max(len(x) for x in arr)

print(max_length)

9


In [23]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using numpy function
import numpy as np
np.random.seed(0)
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [ 685  560  630  193  836  764  708  360   10  724  278  755  805  600
   71  473  601  397  315  706  487  552   88  175  601  850  678  538
  846   73  778  917  116  977  756  710  848  432  449  851  100  985
  178  756  798  660  148  911  424  289  962  266  698  640  545  544
  715  245  152  676  511  460  883  184   29  803  129  129  933   54
  902  551  489  757  274  336  389  618   43  443  544  889  258  322
 1000  938   58  292  871  120  780  431   83   92  897  399  612  566
  909  634]
Mean: 524.97
Median: 551.5
Variance: 82414.08910000001
Standard Deviation: 287.07854169199067


In [24]:
# generate an array of 50 random number between 1 and 100. find the 25th and 75th percentile of the dataset 
import numpy as np

np.random.seed(0)

dataset = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Dataset: [ 45  48  65  68  68  10  84  22  37  88  71  89  89  13  59  66  40  88
  47  89  82  38  26  78  73  10  21  81  70  80  48  65  83 100  89  50
  30  20  20  15  40  33  66  10  58  33  32  75  24  36]
25th Percentile: 32.25
75th Percentile: 77.25


In [25]:
# create two array representing two set of variable. compute the correlation coffecient between these array using numpy corrcoef function.
import numpy as np
np.random.seed(0)

array1 = np.random.rand(100)  
array2 = np.random.rand(100)  
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient:", correlation_coefficient)


Array 1: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481
 0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559
 0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
 0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512
 0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656
 0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212
 0.56660145 0.26538949 0.52324805 0.09394051 0.5759465  

In [26]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])  

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])  
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


In [27]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartile
import numpy as np
np.random.seed(0)
data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50) 
percentile_90 = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Array:", data)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Array: [694 569 639 202 845 773 717 369  19 733 287 764 814 609  80 482 610 406
 324 715 496 561  97 184 610 859 687 547 855  82 787 926 125 986 765 719
 857 441 458 860 109 994 187 765 807 669 157 920 433 298]
10th Percentile: 123.4
50th Percentile (Median): 610.0
90th Percentile: 859.1
First Quartile (25th Percentile): 335.25
Third Quartile (75th Percentile): 771.0


In [28]:
# Create a NumPy array of integers and find the index of a specific element.
import numpy as np
array = np.array([10, 20, 30, 40, 50])

element_to_find = 30
index = np.where(array == element_to_find)[0]

if len(index) > 0:
    print(f"The index of {element_to_find} in the array is: {index[0]}")
else:
    print(f"{element_to_find} not found in the array.")


The index of 30 in the array is: 2


In [29]:
#67. Generate a random NumPy array and sort it in ascending order
import numpy as np
random_array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(random_array)

print("Random Array:", random_array)
print("Sorted Array (ascending order):", sorted_array)


Random Array: [66 10 58 33 32 75 24 36 76 56]
Sorted Array (ascending order): [10 24 32 33 36 56 58 66 75 76]


In [30]:
# Filter elements >20  in the given NumPy array , arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_array = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [31]:
# Filter elements which are divisible by 3 from a given NumPy array , arr = np.array([1, 5, 8, 12, 15])
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
filtered_array = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_array)


Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [32]:
#. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_array)


Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [33]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


In [34]:
# for the given numpy array, performs bytes swapping in place using 'byteswap()'.
# arr = np.array([1,2,3], dtype  np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)
arr.byteswap(True)

print("Array After Byte Swap:", arr)
print("Byte Order After Swap:", arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array After Byte Swap: [16777216 33554432 50331648]
Byte Order After Swap: =


In [35]:
# for the given numpy array, swap its byte order without modifying the orginal array using 'newbyteorder()'.
# arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

swapped_arr = arr.byteswap().newbyteorder()

print("Array After Byte Swap:", swapped_arr)
print("Byte Order After Swap:", swapped_arr.dtype.byteorder)
print("Original Array (unchanged):", arr)


Original Array: [1 2 3]
Original Byte Order: =
Array After Byte Swap: [1 2 3]
Byte Order After Swap: >
Original Array (unchanged): [1 2 3]


In [36]:
# For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`
# arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

import sys
native_byte_order = '<' if sys.byteorder == 'little' else '>'

if byte_order == '=':
    print("Byte swapping is not necessary (native byte order).")
elif byte_order != native_byte_order:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary (matching system byte order).")

print("Byte Order of Array:", byte_order)
print("Native Byte Order of System:", native_byte_order)


Byte swapping is not necessary (native byte order).
Byte Order of Array: =
Native Byte Order of System: <


In [37]:
# Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`
import numpy as np 
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()
copy_arr[0] = 99

print("Original Array (arr1):", arr1)
print("Modified Copy (copy_arr):", copy_arr)


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy (copy_arr): [99  2  3  4  5  6  7  8  9 10]


In [38]:
#  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix
import numpy as np
matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[0:2, 0:2]

view_slice[0, 0] = 999

print("Original Matrix (after modification through view_slice):")
print(matrix)
print("\nView Slice:")
print(view_slice)


Original Matrix (after modification through view_slice):
[[999  35   1]
 [  1  37  54]
 [  6  39  18]]

View Slice:
[[999  35]
 [  1  37]]


In [39]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 1:3]

view_b += 5
print("Original Array (array_a) after modification through view_b:")
print(array_a)
print("\nView Slice (view_b):")
print(view_b)


Original Array (array_a) after modification through view_b:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]

View Slice (view_b):
[[10 11]
 [13 14]]


In [40]:
#  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`
import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

print("Original Array (orig_array) after modification through reshaped_view:")
print(orig_array)
print("\nReshaped View (reshaped_view):")
print(reshaped_view)


Original Array (orig_array) after modification through reshaped_view:
[[99  2  3  4]
 [ 5  6  7  8]]

Reshaped View (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [41]:
#  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data
import numpy as np
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()

print("Original Array (data):")
print(data)
print("\nCopy of Elements Greater Than 5 (data_copy):")
print(data_copy)

if data_copy.size > 0:
    data_copy[0] = 99

print("\nOriginal Array (data) after modification of data_copy:")
print(data)
print("\nModified Copy (data_copy):")
print(data_copy)


Original Array (data):
[[5 9 2 2]
 [8 4 7 8]
 [3 1 4 6]]

Copy of Elements Greater Than 5 (data_copy):
[9 8 7 8 6]

Original Array (data) after modification of data_copy:
[[5 9 2 2]
 [8 4 7 8]
 [3 1 4 6]]

Modified Copy (data_copy):
[99  8  7  8  6]


In [42]:
# Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
import numpy as np
C = np.random.randint(1, 10, size=(3, 2))

D = np.random.randint(1, 10, size=(2, 4))

result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of Matrix Multiplication (C @ D):")
print(result)


Matrix C (3x2):
[[5 5]
 [7 5]
 [5 4]]

Matrix D (2x4):
[[5 5 9 5]
 [4 8 6 6]]

Result of Matrix Multiplication (C @ D):
[[45 65 75 55]
 [55 75 93 65]
 [41 57 69 49]]


In [43]:
# Create a matrix `E` and find its transpose.
import numpy as np
E = np.random.randint(1, 10, size=(3, 4))

E_transpose = E.T

print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 6 4]
 [1 6 1 2]
 [3 5 3 1]]

Transpose of Matrix E:
[[1 1 3]
 [2 6 5]
 [6 1 3]
 [4 2 1]]


In [44]:
# Generate a square matrix `F` and compute its determinan.
import numpy as np
F = np.random.randint(1, 10, size=(3, 3))
determinant = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant)


Matrix F:
[[4 3 1]
 [8 6 1]
 [3 8 3]]

Determinant of Matrix F:
23.0


In [45]:
# Create a square matrix `G` and find its inverse.
import numpy as np
G = np.random.randint(1, 10, size=(3, 3))

try:
    G_inverse = np.linalg.inv(G)
except np.linalg.LinAlgError:
    G_inverse = None

print("Matrix G:")
print(G)

if G_inverse is not None:
    print("\nInverse of Matrix G:")
    print(G_inverse)
else:
    print("\nMatrix G is singular and does not have an inverse.")

Matrix G:
[[3 4 4]
 [3 4 5]
 [2 3 2]]

Inverse of Matrix G:
[[ 7. -4. -4.]
 [-4.  2.  3.]
 [-1.  1.  0.]]


 THANK YOU......